Add layout_stop-watch
mate-academy/layout_stop-watch pull request #1014
Opened 2022-02-24 17:17 UTC by YegorKochetkov

- [DEMO LINK](https://YegorKochetkov.github.io/layout_stop-watch/)

2022-03-04 08:37 UTC, Yurii837 approved these changes

2022-03-04 08:37 UTC, Yurii837 commented on src/styles/main.scss
> +  &__minute {
Ето же секунды

2022-03-04 08:37 UTC, Yurii837 commented on src/styles/main.scss
> +  &__hour {
Соотвецтвенно минуты

2022-03-04 08:37 UTC, Yurii837 commented on src/styles/main.scss
> +    transform-origin: 0 #{$minuteArrowWidth / 2};
можно просто centr bottom

2022-03-04 08:37 UTC, Yurii837 commented on src/styles/main.scss
> +}
Я б не задавал %arrowsPosition rotate(-90deg) соотвецтвенно в @keyframes clock { from 0 to 360}

2022-03-07 16:56 UTC, illiarerun requested changes
Good job, let's wor on fixes now:

2022-03-07 16:56 UTC, illiarerun commented on src/styles/main.scss
> +    animation: clock 60s steps(60) infinite;
your clock doesn't work properly, check it for yourself& a minute clock should make one rotation in 1 hour, not a minute^ and also it should move smoothly

2022-03-07 16:56 UTC, illiarerun commented on src/styles/main.scss
> +    width: $minuteArrowLength;
swap these values and then you can use normal keyframes

2022-03-07 16:56 UTC, illiarerun commented on src/styles/main.scss
> +  }
like that
```suggestion
  from {
    transform: translate(0, -50%) rotate(0deg);
  }

  to {
    transform: translate(0, -50%) rotate(360deg);
  }
```

2022-03-07 16:56 UTC, illiarerun commented on src/styles/main.scss
> +  transform-origin: left center;
and also change it to bottom center

2022-03-08 13:34 UTC, illiarerun approved these changes

2022-11-01 22:07 UTC, closed without merging