watch
mate-academy/layout_stop-watch pull request #1016
Opened 2022-02-26 18:04 UTC by kkiirill

[DEMO LINK](https://kkiirill.github.io/layout_stop-watch/)

2022-03-07 15:51 UTC, Olexandr6 requested changes
Almost done👍, check comments👇

2022-03-07 15:51 UTC, Olexandr6 commented on src/styles/main.scss
> +}
Create a separate file per each BEM block

2022-03-07 15:51 UTC, Olexandr6 commented on src/styles/main.scss
> +  &__minute {
```suggestion
  box-shadow: inset 0 0 10px black;
  
  &__minute {
```

2022-03-09 16:17 UTC, Ihor-Karpyn approved these changes

2022-03-09 16:17 UTC, Ihor-Karpyn commented on src/styles/watch.scss
> +  &__minute {
```suggestion
  &__second {
```

2022-03-09 16:17 UTC, Ihor-Karpyn commented on src/styles/watch.scss
> +  &__second {
```suggestion
  &__minute {
```

2022-03-09 16:17 UTC, Ihor-Karpyn commented on package.json
> +    "@mate-academy/scripts": "^0.9.14",
don't add this

2023-01-03 18:38 UTC, closed without merging