Develop
mate-academy/layout_stop-watch pull request #1081
Opened 2022-04-07 12:16 UTC by yelnikov-andrii

[DEMO LINK](https://yelnikov-andrii.github.io/layout_stop-watch/)

2022-04-08 15:36 UTC, EnjSadman approved these changes
probably you could move some repeating css properies to one mixin.

2022-04-12 11:48 UTC, Denchepornyuk requested changes
<img width="43" alt="Screenshot 2022-04-12 at 14 47 30" src="https://user-images.githubusercontent.com/37452763/162953293-155e5dee-1e21-4b11-9ea8-23fbae8daaba.png">

hide arrows behind center element

2022-04-12 11:48 UTC, Denchepornyuk commented on src/styles/main.scss
> +}
add empty line at the end of file

2022-04-13 07:13 UTC, Denchepornyuk approved these changes

2024-03-19 14:43 UTC, closed without merging