Made stopwatch
mate-academy/layout_stop-watch pull request #1150
Opened 2022-05-17 11:00 UTC by mira1zu

- [DEMO LINK](https://mira1zu.github.io/layout_stop-watch/)

2022-05-18 12:20 UTC, ostapfriend requested changes

2022-05-18 12:20 UTC, ostapfriend commented on src/styles/main.scss
> +}
Привіт, я провірю тобі. Винеси @mixin в окремий файл

2022-05-18 12:20 UTC, ostapfriend commented on src/styles/main.scss
> +}
Оце винеси в файл reset.scss

2022-05-18 12:20 UTC, ostapfriend commented on src/styles/main.scss
> +    height: 256px;
А якщо ти зміниш розміри годинника або ще щось? Тобі треба для такого прописати перемінні,які можна буде швидко змінити

2022-05-18 20:07 UTC, ostapfriend approved these changes

2022-05-19 11:45 UTC, Olexandr6 requested changes
Almost done👍

2022-05-19 11:45 UTC, Olexandr6 commented on src/styles/main.scss
> +.stopwatch {
[Checklist](https://github.com/mate-academy/layout_stop-watch/blob/master/checklist.md) 6th point

2022-05-19 11:45 UTC, Olexandr6 commented on src/styles/main.scss
> +}
For all of these things should be created separate files

2022-05-19 11:45 UTC, Olexandr6 commented on src/styles/main.scss
> +}
+1

2022-05-19 11:45 UTC, Olexandr6 commented on src/styles/main.scss
> +@mixin animation($duration) {
rotation-animation

2022-05-19 12:44 UTC, Olexandr6 approved these changes
Looks much better🔥

2022-12-08 22:08 UTC, closed without merging