commit message
mate-academy/layout_stop-watch pull request #1682
Opened 2022-10-19 23:30 UTC by diamat1997

- [DEMO LINK](https://diamat1997.github.io/layout_stop-watch/)

2022-10-20 11:47 UTC, alexandra-protyanova requested changes

2022-10-20 11:47 UTC, alexandra-protyanova commented on src/styles/blocks/clock.scss
> +  &__center {
let us more variables and mixins for repetitive styles

2022-10-20 18:35 UTC, ivanchuk-yurii requested changes

2022-10-20 18:35 UTC, ivanchuk-yurii commented on src/styles/blocks/clock.scss
> +    width: 15px;
it's also worth to move this into variable

2022-10-20 18:35 UTC, ivanchuk-yurii commented on src/styles/blocks/clock.scss
> +
no empty lines on the file beginning

2022-10-20 18:35 UTC, ivanchuk-yurii commented on src/styles/blocks/clock.scss
> +  }
move repetitive styles into mixin or combining selector

2022-10-21 08:35 UTC, alexandra-protyanova requested changes
You haven't added any changes since last review

2022-10-21 16:03 UTC, closed without merging