initial commit
mate-academy/layout_stop-watch pull request #1709
Opened 2022-10-30 14:43 UTC by olenitut

- [DEMO LINK](https://olenitut.github.io/layout_stop-watch/)

2022-10-30 15:12 UTC, ivanchuk-yurii requested changes

2022-10-30 15:12 UTC, ivanchuk-yurii commented on src/styles/blocks/watch.scss
> +@keyframes rotate {
move animation into separate file

2022-10-30 15:12 UTC, ivanchuk-yurii commented on src/styles/blocks/watch.scss
> +  }
move repetitive styles into common selector

2022-10-30 15:12 UTC, ivanchuk-yurii commented on src/styles/utils/variables.scss
> +$second-height : 300px;
```suggestion
$second-width: 10px;
$second-height: 300px;
```

2022-10-30 15:12 UTC, ivanchuk-yurii commented on src/styles/blocks/watch.scss
> +    min-width: 50px;
just `width`

2022-10-31 14:06 UTC, DarkMistyRoom approved these changes
Good, but be careful about code style

2022-10-31 14:06 UTC, DarkMistyRoom commented on src/styles/utils/variables.scss
> +$second-width: 10px;
```suggestion
$second-width: 10px;
```

2022-11-01 09:17 UTC, Bohdan-Maksymiuk approved these changes

2023-10-18 14:07 UTC, closed without merging