watch was added
mate-academy/layout_stop-watch pull request #1782
Opened 2022-11-11 21:56 UTC by batstolya

- [DEMO LINK](https://batstolya.github.io/layout_stop-watch/)

2022-11-12 22:42 UTC, DiDemkiv requested changes
Small mistakes, but otherwise looks good to me! 🔥 Good job

2022-11-12 22:42 UTC, DiDemkiv commented on src/styles/blocks/clock.scss
> +  }
you can apply this once in the "clock" class since it's the parent element

2022-11-12 22:42 UTC, DiDemkiv commented on src/styles/blocks/clock.scss
> +
```suggestion
```

2022-11-12 22:42 UTC, DiDemkiv commented on src/styles/blocks/clock.scss
> +}
let's create a separate file for this block

2022-11-12 22:42 UTC, DiDemkiv commented on src/styles/blocks/clock.scss
> +  margin: 0 auto;
it's wrong to use margin in bem block. Let's remove it here and add justify-content: center to the wrapper :)

2022-11-12 22:42 UTC, DiDemkiv commented on src/styles/blocks/clock.scss
> +    display: block;
not necessary to add display: block

2022-11-13 12:01 UTC, DiDemkiv approved these changes
Good job! 🔥

2022-11-14 08:27 UTC, valerii-derkach requested changes
Good job!

just small fix

2022-11-14 08:27 UTC, valerii-derkach commented on src/styles/blocks/clock.scss
> +      background: red;
let's make the arrows (hands) shorter, that both should be inside the circle

2022-11-14 12:43 UTC, valerii-derkach approved these changes

2026-07-13 23:08 UTC, closed without merging