Stop-watch was created
mate-academy/layout_stop-watch pull request #1882
Opened 2022-12-11 18:18 UTC by NazariiAlieksieiev

- [DEMO LINK](https://NazariiAlieksieiev.github.io/layout_stop-watch/)

2022-12-11 21:11 UTC, ivanchuk-yurii requested changes

2022-12-11 21:11 UTC, ivanchuk-yurii commented on src/styles/blocks/stop-watch.scss
> +@keyframes rotate {
move this into separate file

2022-12-11 21:11 UTC, ivanchuk-yurii commented on src/styles/blocks/stop-watch.scss
> +  }
move repetitive styles into common selector

2022-12-11 21:11 UTC, ivanchuk-yurii commented on src/styles/blocks/stop-watch.scss
> +.stop-watch {
add border so it will look like watch

2022-12-12 17:20 UTC, Viktor-Kost approved these changes

2024-07-27 11:24 UTC, closed without merging