Fixed some mistakes
mate-academy/layout_stop-watch pull request #1938
Opened 2022-12-18 14:53 UTC by SashaViun

- [DEMO LINK](https://SashaViun.github.io/layout_stop-watch/)

2022-12-19 11:43 UTC, PolinaSukhorukova commented
Good job! 🔥

2022-12-19 11:43 UTC, PolinaSukhorukova requested changes
Second hand unnaturally slows down at the end of the minute.  Try to add animation-timing-function.

2022-12-23 09:48 UTC, Anna-Tkachenko requested changes
Why did you set border-radius 45% for the main container? let's make watch the circle, not some other figure

2022-12-23 09:48 UTC, Anna-Tkachenko commented on src/styles/blocks/watch.scss
> +    top: 14%;
it's not clear what these value means
will be better to calculate them somehow depending on the size of watch / hands

2022-12-23 09:48 UTC, Anna-Tkachenko commented on src/styles/blocks/watch.scss
> +    top: 20%;
same here

2022-12-27 12:05 UTC, alexandra-protyanova approved these changes
Good job 👍

2022-12-27 12:05 UTC, alexandra-protyanova commented on src/styles/utils/_variables.scss
> +@keyframes seconds {
You have 2 absolutely the same keyframes, you can use one of them and nothing will change

2023-03-23 09:17 UTC, closed without merging