Created stop-watch
mate-academy/layout_stop-watch pull request #1987
Opened 2023-01-12 09:55 UTC by natalia-matash

https://natalia-matash.github.io/layout_stop-watch/

2023-01-13 10:17 UTC, Virass requested changes

2023-01-13 10:17 UTC, Virass commented on src/styles/blocks/reset.scss
> +}
It is not the optimal solution. Not use * for clear geometry (padding, margin...) for elements

2023-01-13 10:17 UTC, Virass commented on src/styles/blocks/stop-watch.scss
> +  }
Code for minute-arrow and second-arrow repeated. Use the DRY principle. Rename and use once animation.

2023-01-14 13:53 UTC, agniya-i approved these changes

2023-02-01 12:01 UTC, closed without merging