silution
mate-academy/layout_stop-watch pull request #2026
Opened 2023-01-24 14:29 UTC by Zelinskyi-Serhii

- [DEMO LINK](https://Zelinskyi-Serhii.github.io/layout_stop-watch/)
Solution*

2023-02-02 11:10 UTC, kirill-vypirovskyi approved these changes

2023-02-02 11:10 UTC, kirill-vypirovskyi commented on src/styles/clock.scss
> +  }
You can do it as %placeholder and don't add one more class to arrows

2023-02-03 22:00 UTC, Ambulence approved these changes
Good job!

2023-02-13 14:42 UTC, Andr1yK requested changes

2023-02-13 14:42 UTC, Andr1yK commented on src/index.html
> +      <div class="clock__minute clock-arrows"></div>
```suggestion
      <div class="clock__minute clock-arrow"></div>
```

2023-02-13 14:42 UTC, Andr1yK commented on src/styles/clock.scss
> +  &-arrows {
wow.. why do u style block inside block?

2023-02-17 08:10 UTC, Andr1yK approved these changes

2023-07-12 20:27 UTC, closed without merging