timer
mate-academy/layout_stop-watch pull request #2072
Opened 2023-02-03 15:41 UTC by Faridun92

- [DEMO LINK](https://Faridun92.github.io/layout_stop-watch/)

2023-02-03 19:37 UTC, SanyaBratashchuk requested changes
hands should rotate

2023-02-04 10:09 UTC, ViktorHavryliuk requested changes

2023-02-04 10:09 UTC, ViktorHavryliuk commented on src/styles/blocks/timer.scss
> +@keyframes move {
Move keframes into separate _keyframes.scss file

2023-02-04 10:09 UTC, ViktorHavryliuk commented on src/styles/blocks/timer.scss
> +    animation: move 45s 15s linear infinite;
Currently your minute hand moves with the same speed as seconds hand, please fix that

2023-02-04 10:09 UTC, ViktorHavryliuk commented on src/styles/utils/_variables.scss
> +$trans10s: 10s;
It's not recommended to hardcode number values into your var names, as if the value gets changed in the future you will have to change the name too.
Better name it something like "transitionLong"/"transitionShort", or whatever you find to sound reasonable

2023-02-04 14:03 UTC, SanyaBratashchuk requested changes
second hand must make a full turn in one minute, minute hand in one hour

2023-02-05 09:10 UTC, SanyaBratashchuk approved these changes

2023-02-05 09:10 UTC, SanyaBratashchuk commented on src/styles/utils/_variables.scss
> +$absolute: absolute;
There is no sense in this variables

2023-02-05 09:10 UTC, SanyaBratashchuk commented on src/styles/utils/_variables.scss
> +$center: center;
the same

2026-08-18 22:32 UTC, closed without merging