watch was created
mate-academy/layout_stop-watch pull request #2124
Opened 2023-02-19 19:59 UTC by BilokonYaroslav

- [DEMO LINK](https://BilokonYaroslav.github.io/layout_stop-watch/)

2023-02-20 09:39 UTC, OlEzhA0 approved these changes
check your UI)
<img width="296" alt="Screenshot 2023-02-20 at 11 38 37 AM" src="https://user-images.githubusercontent.com/60295799/220068691-33934b35-7f4b-45a7-ad5d-4875e7063ed1.png">
hey! GJ

2023-02-20 09:39 UTC, OlEzhA0 commented on src/styles/blocks/_watch.scss
> +  @keyframes rotate {
move keyframe to separate file

2023-02-21 05:29 UTC, BilokonYaroslav commented on src/styles/blocks/_watch.scss
> +  @keyframes rotate {
What You mean "check your UI)"?

2023-02-22 08:31 UTC, OleziO requested changes
The red clock hand is the second hand, and the blue hand is the minute hand. Fix it

2023-02-22 13:42 UTC, IvanFesenko approved these changes

2023-12-10 12:28 UTC, closed without merging