done
mate-academy/layout_stop-watch pull request #2545
Opened 2023-06-26 19:51 UTC by asya-bm

- [DEMO LINK](https://asya-bm.github.io/layout_stop-watch/)

2023-06-26 20:05 UTC, Viktor-Kost requested changes
GJ!
Some minor fixes needed

2023-06-26 20:05 UTC, Viktor-Kost commented on src/styles/watch.scss
> +}
there are the same animations, so no needs to use two different ones

2023-06-26 20:05 UTC, Viktor-Kost commented on src/styles/variables.scss
> +  border-bottom-left-radius: 90%;
```suggestion
  border-radius: 90%;
```

2023-06-27 10:40 UTC, demetrxx approved these changes
Well done 👍 Go ahead!

2024-07-30 14:05 UTC, closed without merging