add task solution
mate-academy/layout_stop-watch pull request #2572
Opened 2023-07-07 09:21 UTC by patryk-babon

- [DEMO LINK](https://patryk-babon.github.io/layout_stop-watch/)

2023-07-12 07:34 UTC, choeqq requested changes
Almost there 😄

2023-07-12 07:34 UTC, choeqq commented on src/styles/utils/_mixins.scss
I would create separate animation for each hand - seconds hand is looking pretty smooth, when the other 2 are just jumping over few pixels :/

2023-07-12 07:45 UTC, patryk-babon commented on src/styles/utils/_mixins.scss
This is a deliberate effect. The hour hand jumps every hour and the minute hand jumps every minute. This is the effect I wanted and I like it.

The animation can be easily customized as you can see in the example below:

```css
@include rotate($seconds-rotation-time, linear);

@include rotate($minutes-rotation-time, steps(60));
```

2023-07-17 06:11 UTC, choeqq approved these changes
I don't have any other adjustments, nicely done! 🚀

2024-09-01 00:29 UTC, closed without merging