Develop
mate-academy/layout_stop-watch pull request #2831
Opened 2023-10-13 11:50 UTC by DidenkoAK

- [DEMO LINK](https://DidenkoAK.github.io/layout_stop-watch/)

To demonstrate 5c, point to the green arrow
To demonstrate 60 seconds, press and hold one of the arrows.

2023-10-13 12:13 UTC, anastasiiavorobiova requested changes
Great start! The hands should move infinitely and match the task requirements
<img width="481" alt="Screenshot 2023-10-13 at 15 13 19" src="https://github.com/mate-academy/layout_stop-watch/assets/135232001/96515cbe-d063-4234-b365-96d83fc9a411">

2023-10-13 12:13 UTC, anastasiiavorobiova commented on src/styles/main.scss
> +}
It's enough to use one keyframe in this task and change the time of animation

2023-10-16 10:46 UTC, anastasiiavorobiova requested changes
Great progress! The hand moves back unexpectedly, consider fixing it. Hands move a bit slowly, consider taking the time for animation from the task requirements. Feel free to ask for help in the chat

2023-10-19 14:52 UTC, sTorba24 approved these changes

2026-03-11 22:43 UTC, closed without merging