add task solution
mate-academy/layout_stop-watch pull request #3029
Opened 2024-01-15 13:57 UTC by Allanpt

- [DEMO LINK](https://Allanpt.github.io/layout_stop-watch/)

- [x] Keyframes implemented using from/to + transform with rotate property
- [x] Stopwatch is centered and has correct arrows size
- [x] All `Typical Mistakes` from `BEM` lesson theory are checked.
- [x] Code follows all the [Code Style Rules ❗️](https://mate-academy.github.io/layout_task-guideline/html-css-code-style-rules)

2024-02-20 14:12 UTC, jv-aquino requested changes
Nice and concise code, following the guidelines of a good front end dev, there's just two things that you should check out

2024-02-20 14:12 UTC, jv-aquino commented on src/styles/main.scss
> +    transform: rotate(90deg) translate(-0.1%, -0.1%);
The translate here is probably unnecessary

2024-02-20 14:12 UTC, jv-aquino commented on src/index.html
> +      <div class="hour-pointer"></div>
You could use BEM naming conventions here

2024-02-28 21:08 UTC, closed without merging

2024-03-04 17:52 UTC, Allanpt commented
Ok, i think it's done now LOLOLOLOLO

2024-03-06 20:07 UTC, pedro-ruas approved these changes
Great Job!