Solution
mate-academy/layout_stop-watch pull request #480
Opened 2021-02-14 13:03 UTC by TarasOleksyshyn

- [DEMO LINK](https://TarasOleksyshyn.github.io/layout_stop-watch/)

2021-02-14 14:19 UTC, haiduk2019 commented on src/styles/watch-style.scss
> +  animation: watch 3600s infinite linear;
Нужно задать задержку анимации, чтобы она сработала только через 1 минуту, когда секундная стрелка пройдет полный круг

2021-02-14 14:20 UTC, haiduk2019 requested changes
Нужно задать задержку анимации, чтобы она сработала только через 1 минуту, когда секундная стрелка пройдет полный круг

2021-02-14 14:39 UTC, TarasOleksyshyn commented on src/styles/watch-style.scss
> +  animation: watch 3600s infinite linear;
для чого? хвилинна стрілка, рухається плавно з секундною.

2021-02-15 09:45 UTC, danheim requested changes

2021-02-15 09:45 UTC, danheim commented on src/index.html
> +    </div>
use BEM

watch
watch__minute
watch__second

2021-02-15 09:45 UTC, danheim commented on src/styles/watch-style.scss
> +.center {
используй вложенность через амперсант

2021-02-15 09:45 UTC, danheim commented on src/styles/watch-style.scss
> +  left: -8px;
negative values look weird, don't do it

2021-02-15 09:45 UTC, danheim commented on src/styles/watch-style.scss
> +  top: -120px;
remove negative values

2021-02-15 15:38 UTC, danheim approved these changes

2023-03-15 14:01 UTC, closed without merging