add solution stop_watch
mate-academy/layout_stop-watch pull request #526
Opened 2021-04-23 17:44 UTC by nevskyy

[DEMO LINK](https://nevskyy.github.io/layout_stop-watch/)

2021-04-26 10:46 UTC, vpolets requested changes

2021-04-26 10:46 UTC, vpolets commented on src/styles/blocks/watch_content.scss
> +  }
штука з тінями якось ту мач)

2021-04-26 10:46 UTC, vpolets commented on src/styles/blocks/watch_content.scss
> +    z-index: 2;
спільні стилі винеси в arrow клас

2021-04-28 18:11 UTC, nevskyy commented on src/styles/blocks/watch_content.scss
> +  }
Влад, привіт. То, якщо уявити що сонце десь в верхньому лівому куту екрана, і коли рухаються стрілка то міняються Їх тіні в залежності від сонця. Якщо шо затру.

2021-04-29 14:38 UTC, vpolets approved these changes
Підняв настрій) Прийняв)

2024-12-23 13:11 UTC, closed without merging