watch
mate-academy/layout_stop-watch pull request #646
Opened 2021-07-16 10:22 UTC by anton-forzun

- [DEMO LINK](https://anton-forzun.github.io/layout_stop-watch/)

2021-07-16 11:46 UTC, mykola-yarchuk requested changes
https://user-images.githubusercontent.com/35385361/125942693-c7ee717b-3e5c-42b2-a23e-243860291634.mov

![image](https://user-images.githubusercontent.com/35385361/125942754-e53155c6-126d-4a1b-b822-edb75ec02364.png)

в завданні трохи не так, зроби по дизайну

2021-07-19 10:05 UTC, vkryvytskyy requested changes
https://user-images.githubusercontent.com/38065883/126143578-a8d3e54e-5d39-478b-926b-770f75ab68d3.mov

Сделай так чтобы часы на любом экране выглядели адекватно

2021-07-20 12:15 UTC, vkryvytskyy reviewed
![image](https://user-images.githubusercontent.com/38065883/126322062-9b7814ff-1b6a-4a0f-8144-4be741bb471a.png)
Стрелки не по центру

2021-07-20 12:15 UTC, vkryvytskyy requested changes
Поправь стрелки

2021-07-20 12:15 UTC, vkryvytskyy commented on src/styles/main.scss
> +    left: 51%;
Почему 51?

2021-07-20 12:15 UTC, vkryvytskyy commented on src/styles/main.scss
> +    left: 51% ;
Почему 51?

2021-07-20 13:25 UTC, vkryvytskyy requested changes
![image](https://user-images.githubusercontent.com/38065883/126331821-eadb9a1f-9958-4cdd-813b-e23fbb2da4e3.png)
Теперь то же самое, только в другую сторону

2021-07-21 12:12 UTC, vkryvytskyy approved these changes

2021-07-21 12:59 UTC, closed without merging