stopwatch solution
mate-academy/layout_stop-watch pull request #842
Opened 2021-11-25 13:52 UTC by levix2l

- [DEMO LINK](https://levix2l.github.io/layout_stop-watch/)

2021-11-26 15:19 UTC, pasha-melnyk requested changes

2021-11-26 15:19 UTC, pasha-melnyk commented on src/styles/main.scss
> +    background-color: #cf4c4c;
стоит сделать миксины для элементов часов

2021-11-26 15:40 UTC, pasha-melnyk approved these changes

2021-11-29 10:46 UTC, Elena-brv requested changes
it should be minute and second arrows (not seconds and milliseconds)

2021-11-29 10:46 UTC, Elena-brv commented on src/styles/animations.scss
> +    transform: rotate(180deg);
maybe 0deg and 360deg?)

2021-11-29 10:46 UTC, Elena-brv commented on src/styles/utils/_mixin.scss
> +@mixin clock ($width, $height, $top, $left, $background-color, $border-radius) {
```suggestion
@mixin time-hand ($width, $height, $top, $left, $background-color, $border-radius) {
```

2021-11-29 20:41 UTC, Elena-brv requested changes
не исправил
![image](https://user-images.githubusercontent.com/64437769/143939867-3b4352c0-3459-4a4f-817a-41c269c8872f.png)

2021-11-29 21:11 UTC, levix2l commented
> не исправил ![image](https://user-images.githubusercontent.com/64437769/143939867-3b4352c0-3459-4a4f-817a-41c269c8872f.png)

I'm sorry. A pretty dumb mistake from my side.

2021-11-30 06:18 UTC, Elena-brv approved these changes

2026-06-20 23:02 UTC, closed without merging