stop-watch_solution
mate-academy/layout_stop-watch pull request #856
Opened 2021-11-26 12:36 UTC by andrii-koptiev

2021-11-26 13:14 UTC, Viktor9r approved these changes
Всё в порядке. Не к чему пристать.

2021-11-29 10:28 UTC, Elena-brv requested changes
- check styles, it is visible that an arrow not on the center of the circle 
![image](https://user-images.githubusercontent.com/64437769/143850948-8f1cdaca-f746-4e56-8432-918dc76089bb.png)

2021-11-29 10:28 UTC, Elena-brv commented on src/styles/blocks/watch.scss
> +    }
no need, you can specify it simply (all places)

 ```suggestion
    animation-duration: 3600s;
```

2021-11-29 20:34 UTC, Elena-brv approved these changes

2023-09-26 21:32 UTC, closed without merging