BEST_CLOCK
mate-academy/layout_stop-watch pull request #871
Opened 2021-11-28 20:25 UTC by MaksimusCRS

- [DEMO LINK](https://MaksimusCRS.github.io/layout_stop-watch/)

2021-11-29 11:38 UTC, luckdenny approved these changes

2021-11-29 11:38 UTC, luckdenny commented on src/styles/main.scss
> +}
можно было задать общую анимацию для двух стрелок.

2021-11-29 20:40 UTC, Elena-brv requested changes

2021-11-29 20:40 UTC, Elena-brv commented on src/styles/main.scss
> +    margin: 25% auto;
why 25%?

2021-11-29 20:40 UTC, Elena-brv commented on src/index.html
> +    <section class="watch watch--position--center">
```suggestion
    <section class="watch watch--position-center">
```

2021-11-29 20:40 UTC, Elena-brv commented on src/styles/main.scss
> +$color_blue: rgb(0, 106, 141);
```suggestion
$color-blue: rgb(0, 106, 141);
```

2021-11-29 20:40 UTC, Elena-brv commented on src/styles/main.scss
> +}
do according to advice

2021-11-30 09:39 UTC, luckdenny approved these changes

2021-11-30 16:12 UTC, Elena-brv approved these changes

2022-10-20 17:52 UTC, closed without merging