Develop
mate-academy/layout_stop-watch pull request #884
Opened 2021-12-12 13:07 UTC by sever2kk

2021-12-13 10:52 UTC, danylo-onishchuk requested changes
не вижу ссылку на проект

2021-12-26 18:42 UTC, sever2kk commented
- [DEMO LINK](https://<sever2kk>.github.io/layout_stop-watch/)

2021-12-28 14:58 UTC, aliceblunt8 approved these changes

2021-12-28 14:58 UTC, aliceblunt8 commented on src/styles/main.scss
> +}
let's add all variables, mixins and extends to separate files

2026-07-17 03:06 UTC, closed without merging